services:
  postgres:
    image: 17.2-alpine
    container_name: postdb
    environment:
      POSTGRES_USER: ju
      POSTGRES_PASSWORD: ju
      POSTGRES_DB: ju
    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume:

networks:
  ju_net:
    name: ju_net
    driver: bridge
