import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const vazir = localFont({
  src: '../fonts/vazirmatn-vf.ttf',
  variable: '--font-vazir',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir='rtl' lang='fa' suppressHydrationWarning>
      <body className={vazir.className}>{children}</body>
    </html>
  );
}
